// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/rgraphql/rgraphql/rgraphql.proto

package rgraphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RGQLPrimitive_Kind int32

const (
	RGQLPrimitive_PRIMITIVE_KIND_NULL   RGQLPrimitive_Kind = 0
	RGQLPrimitive_PRIMITIVE_KIND_INT    RGQLPrimitive_Kind = 1
	RGQLPrimitive_PRIMITIVE_KIND_FLOAT  RGQLPrimitive_Kind = 2
	RGQLPrimitive_PRIMITIVE_KIND_STRING RGQLPrimitive_Kind = 3
	RGQLPrimitive_PRIMITIVE_KIND_BOOL   RGQLPrimitive_Kind = 4
	RGQLPrimitive_PRIMITIVE_KIND_OBJECT RGQLPrimitive_Kind = 5
	// A marker for an empty array.
	RGQLPrimitive_PRIMITIVE_KIND_ARRAY RGQLPrimitive_Kind = 6
)

var RGQLPrimitive_Kind_name = map[int32]string{
	0: "PRIMITIVE_KIND_NULL",
	1: "PRIMITIVE_KIND_INT",
	2: "PRIMITIVE_KIND_FLOAT",
	3: "PRIMITIVE_KIND_STRING",
	4: "PRIMITIVE_KIND_BOOL",
	5: "PRIMITIVE_KIND_OBJECT",
	6: "PRIMITIVE_KIND_ARRAY",
}

var RGQLPrimitive_Kind_value = map[string]int32{
	"PRIMITIVE_KIND_NULL":   0,
	"PRIMITIVE_KIND_INT":    1,
	"PRIMITIVE_KIND_FLOAT":  2,
	"PRIMITIVE_KIND_STRING": 3,
	"PRIMITIVE_KIND_BOOL":   4,
	"PRIMITIVE_KIND_OBJECT": 5,
	"PRIMITIVE_KIND_ARRAY":  6,
}

func (x RGQLPrimitive_Kind) String() string {
	return proto.EnumName(RGQLPrimitive_Kind_name, int32(x))
}

func (RGQLPrimitive_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{4, 0}
}

type RGQLQueryTreeMutation_SubtreeOperation int32

const (
	// Add a child tree to the subtree.
	RGQLQueryTreeMutation_SUBTREE_ADD_CHILD RGQLQueryTreeMutation_SubtreeOperation = 0
	// Delete a tree node and all children.
	RGQLQueryTreeMutation_SUBTREE_DELETE RGQLQueryTreeMutation_SubtreeOperation = 1
)

var RGQLQueryTreeMutation_SubtreeOperation_name = map[int32]string{
	0: "SUBTREE_ADD_CHILD",
	1: "SUBTREE_DELETE",
}

var RGQLQueryTreeMutation_SubtreeOperation_value = map[string]int32{
	"SUBTREE_ADD_CHILD": 0,
	"SUBTREE_DELETE":    1,
}

func (x RGQLQueryTreeMutation_SubtreeOperation) String() string {
	return proto.EnumName(RGQLQueryTreeMutation_SubtreeOperation_name, int32(x))
}

func (RGQLQueryTreeMutation_SubtreeOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{7, 0}
}

type RGQLValueInit_CacheStrategy int32

const (
	RGQLValueInit_CACHE_LRU RGQLValueInit_CacheStrategy = 0
)

var RGQLValueInit_CacheStrategy_name = map[int32]string{
	0: "CACHE_LRU",
}

var RGQLValueInit_CacheStrategy_value = map[string]int32{
	"CACHE_LRU": 0,
}

func (x RGQLValueInit_CacheStrategy) String() string {
	return proto.EnumName(RGQLValueInit_CacheStrategy_name, int32(x))
}

func (RGQLValueInit_CacheStrategy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{10, 0}
}

type RGQLQueryFieldDirective struct {
	// Directive name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional arguments.
	Args                 []*FieldArgument `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RGQLQueryFieldDirective) Reset()         { *m = RGQLQueryFieldDirective{} }
func (m *RGQLQueryFieldDirective) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryFieldDirective) ProtoMessage()    {}
func (*RGQLQueryFieldDirective) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{0}
}

func (m *RGQLQueryFieldDirective) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryFieldDirective.Unmarshal(m, b)
}
func (m *RGQLQueryFieldDirective) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryFieldDirective.Marshal(b, m, deterministic)
}
func (m *RGQLQueryFieldDirective) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryFieldDirective.Merge(m, src)
}
func (m *RGQLQueryFieldDirective) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryFieldDirective.Size(m)
}
func (m *RGQLQueryFieldDirective) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryFieldDirective.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryFieldDirective proto.InternalMessageInfo

func (m *RGQLQueryFieldDirective) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RGQLQueryFieldDirective) GetArgs() []*FieldArgument {
	if m != nil {
		return m.Args
	}
	return nil
}

type RGQLQueryTreeNode struct {
	// Integer ID of the node.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the field this node represents.
	FieldName string `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Arguments.
	Args []*FieldArgument `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// Directives
	Directive []*RGQLQueryFieldDirective `protobuf:"bytes,4,rep,name=directive,proto3" json:"directive,omitempty"`
	// Children
	Children             []*RGQLQueryTreeNode `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RGQLQueryTreeNode) Reset()         { *m = RGQLQueryTreeNode{} }
func (m *RGQLQueryTreeNode) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryTreeNode) ProtoMessage()    {}
func (*RGQLQueryTreeNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{1}
}

func (m *RGQLQueryTreeNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryTreeNode.Unmarshal(m, b)
}
func (m *RGQLQueryTreeNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryTreeNode.Marshal(b, m, deterministic)
}
func (m *RGQLQueryTreeNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryTreeNode.Merge(m, src)
}
func (m *RGQLQueryTreeNode) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryTreeNode.Size(m)
}
func (m *RGQLQueryTreeNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryTreeNode.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryTreeNode proto.InternalMessageInfo

func (m *RGQLQueryTreeNode) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RGQLQueryTreeNode) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *RGQLQueryTreeNode) GetArgs() []*FieldArgument {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RGQLQueryTreeNode) GetDirective() []*RGQLQueryFieldDirective {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *RGQLQueryTreeNode) GetChildren() []*RGQLQueryTreeNode {
	if m != nil {
		return m.Children
	}
	return nil
}

type FieldArgument struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VariableId           uint32   `protobuf:"varint,2,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldArgument) Reset()         { *m = FieldArgument{} }
func (m *FieldArgument) String() string { return proto.CompactTextString(m) }
func (*FieldArgument) ProtoMessage()    {}
func (*FieldArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{2}
}

func (m *FieldArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldArgument.Unmarshal(m, b)
}
func (m *FieldArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldArgument.Marshal(b, m, deterministic)
}
func (m *FieldArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldArgument.Merge(m, src)
}
func (m *FieldArgument) XXX_Size() int {
	return xxx_messageInfo_FieldArgument.Size(m)
}
func (m *FieldArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldArgument.DiscardUnknown(m)
}

var xxx_messageInfo_FieldArgument proto.InternalMessageInfo

func (m *FieldArgument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldArgument) GetVariableId() uint32 {
	if m != nil {
		return m.VariableId
	}
	return 0
}

type ASTVariable struct {
	Id                   uint32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                *RGQLPrimitive `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ASTVariable) Reset()         { *m = ASTVariable{} }
func (m *ASTVariable) String() string { return proto.CompactTextString(m) }
func (*ASTVariable) ProtoMessage()    {}
func (*ASTVariable) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{3}
}

func (m *ASTVariable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASTVariable.Unmarshal(m, b)
}
func (m *ASTVariable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASTVariable.Marshal(b, m, deterministic)
}
func (m *ASTVariable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASTVariable.Merge(m, src)
}
func (m *ASTVariable) XXX_Size() int {
	return xxx_messageInfo_ASTVariable.Size(m)
}
func (m *ASTVariable) XXX_DiscardUnknown() {
	xxx_messageInfo_ASTVariable.DiscardUnknown(m)
}

var xxx_messageInfo_ASTVariable proto.InternalMessageInfo

func (m *ASTVariable) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ASTVariable) GetValue() *RGQLPrimitive {
	if m != nil {
		return m.Value
	}
	return nil
}

type RGQLPrimitive struct {
	Kind                 RGQLPrimitive_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=rgraphql.RGQLPrimitive_Kind" json:"kind,omitempty"`
	IntValue             int32              `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3" json:"int_value,omitempty"`
	FloatValue           float64            `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	StringValue          string             `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BoolValue            bool               `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RGQLPrimitive) Reset()         { *m = RGQLPrimitive{} }
func (m *RGQLPrimitive) String() string { return proto.CompactTextString(m) }
func (*RGQLPrimitive) ProtoMessage()    {}
func (*RGQLPrimitive) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{4}
}

func (m *RGQLPrimitive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLPrimitive.Unmarshal(m, b)
}
func (m *RGQLPrimitive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLPrimitive.Marshal(b, m, deterministic)
}
func (m *RGQLPrimitive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLPrimitive.Merge(m, src)
}
func (m *RGQLPrimitive) XXX_Size() int {
	return xxx_messageInfo_RGQLPrimitive.Size(m)
}
func (m *RGQLPrimitive) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLPrimitive.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLPrimitive proto.InternalMessageInfo

func (m *RGQLPrimitive) GetKind() RGQLPrimitive_Kind {
	if m != nil {
		return m.Kind
	}
	return RGQLPrimitive_PRIMITIVE_KIND_NULL
}

func (m *RGQLPrimitive) GetIntValue() int32 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *RGQLPrimitive) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *RGQLPrimitive) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *RGQLPrimitive) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

// Messages
type RGQLClientMessage struct {
	InitQuery            *RGQLQueryInit         `protobuf:"bytes,1,opt,name=init_query,json=initQuery,proto3" json:"init_query,omitempty"`
	MutateTree           *RGQLQueryTreeMutation `protobuf:"bytes,2,opt,name=mutate_tree,json=mutateTree,proto3" json:"mutate_tree,omitempty"`
	FinishQuery          *RGQLQueryFinish       `protobuf:"bytes,3,opt,name=finish_query,json=finishQuery,proto3" json:"finish_query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RGQLClientMessage) Reset()         { *m = RGQLClientMessage{} }
func (m *RGQLClientMessage) String() string { return proto.CompactTextString(m) }
func (*RGQLClientMessage) ProtoMessage()    {}
func (*RGQLClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{5}
}

func (m *RGQLClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLClientMessage.Unmarshal(m, b)
}
func (m *RGQLClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLClientMessage.Marshal(b, m, deterministic)
}
func (m *RGQLClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLClientMessage.Merge(m, src)
}
func (m *RGQLClientMessage) XXX_Size() int {
	return xxx_messageInfo_RGQLClientMessage.Size(m)
}
func (m *RGQLClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLClientMessage proto.InternalMessageInfo

func (m *RGQLClientMessage) GetInitQuery() *RGQLQueryInit {
	if m != nil {
		return m.InitQuery
	}
	return nil
}

func (m *RGQLClientMessage) GetMutateTree() *RGQLQueryTreeMutation {
	if m != nil {
		return m.MutateTree
	}
	return nil
}

func (m *RGQLClientMessage) GetFinishQuery() *RGQLQueryFinish {
	if m != nil {
		return m.FinishQuery
	}
	return nil
}

type RGQLQueryInit struct {
	// The ID of this query.
	QueryId uint32 `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// Force serial for this query?
	// Note: serial queries execute as soon as the first mutation arrives, and cannot be updated.
	ForceSerial bool `protobuf:"varint,2,opt,name=force_serial,json=forceSerial,proto3" json:"force_serial,omitempty"`
	// Operation type, i.e. query, mutation, etc.
	OperationType        string   `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLQueryInit) Reset()         { *m = RGQLQueryInit{} }
func (m *RGQLQueryInit) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryInit) ProtoMessage()    {}
func (*RGQLQueryInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{6}
}

func (m *RGQLQueryInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryInit.Unmarshal(m, b)
}
func (m *RGQLQueryInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryInit.Marshal(b, m, deterministic)
}
func (m *RGQLQueryInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryInit.Merge(m, src)
}
func (m *RGQLQueryInit) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryInit.Size(m)
}
func (m *RGQLQueryInit) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryInit.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryInit proto.InternalMessageInfo

func (m *RGQLQueryInit) GetQueryId() uint32 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *RGQLQueryInit) GetForceSerial() bool {
	if m != nil {
		return m.ForceSerial
	}
	return false
}

func (m *RGQLQueryInit) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

type RGQLQueryTreeMutation struct {
	// The ID of this query.
	QueryId uint32 `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// All node mutations in this step.
	NodeMutation []*RGQLQueryTreeMutation_NodeMutation `protobuf:"bytes,2,rep,name=node_mutation,json=nodeMutation,proto3" json:"node_mutation,omitempty"`
	// Any new variables.
	Variables            []*ASTVariable `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RGQLQueryTreeMutation) Reset()         { *m = RGQLQueryTreeMutation{} }
func (m *RGQLQueryTreeMutation) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryTreeMutation) ProtoMessage()    {}
func (*RGQLQueryTreeMutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{7}
}

func (m *RGQLQueryTreeMutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryTreeMutation.Unmarshal(m, b)
}
func (m *RGQLQueryTreeMutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryTreeMutation.Marshal(b, m, deterministic)
}
func (m *RGQLQueryTreeMutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryTreeMutation.Merge(m, src)
}
func (m *RGQLQueryTreeMutation) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryTreeMutation.Size(m)
}
func (m *RGQLQueryTreeMutation) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryTreeMutation.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryTreeMutation proto.InternalMessageInfo

func (m *RGQLQueryTreeMutation) GetQueryId() uint32 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *RGQLQueryTreeMutation) GetNodeMutation() []*RGQLQueryTreeMutation_NodeMutation {
	if m != nil {
		return m.NodeMutation
	}
	return nil
}

func (m *RGQLQueryTreeMutation) GetVariables() []*ASTVariable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type RGQLQueryTreeMutation_NodeMutation struct {
	// ID of the node we are operating on.
	NodeId uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Operation we are taking.
	Operation RGQLQueryTreeMutation_SubtreeOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=rgraphql.RGQLQueryTreeMutation_SubtreeOperation" json:"operation,omitempty"`
	// The new node tree to add, if we are adding a child.
	Node                 *RGQLQueryTreeNode `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RGQLQueryTreeMutation_NodeMutation) Reset()         { *m = RGQLQueryTreeMutation_NodeMutation{} }
func (m *RGQLQueryTreeMutation_NodeMutation) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryTreeMutation_NodeMutation) ProtoMessage()    {}
func (*RGQLQueryTreeMutation_NodeMutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{7, 0}
}

func (m *RGQLQueryTreeMutation_NodeMutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation.Unmarshal(m, b)
}
func (m *RGQLQueryTreeMutation_NodeMutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation.Marshal(b, m, deterministic)
}
func (m *RGQLQueryTreeMutation_NodeMutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation.Merge(m, src)
}
func (m *RGQLQueryTreeMutation_NodeMutation) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation.Size(m)
}
func (m *RGQLQueryTreeMutation_NodeMutation) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryTreeMutation_NodeMutation proto.InternalMessageInfo

func (m *RGQLQueryTreeMutation_NodeMutation) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *RGQLQueryTreeMutation_NodeMutation) GetOperation() RGQLQueryTreeMutation_SubtreeOperation {
	if m != nil {
		return m.Operation
	}
	return RGQLQueryTreeMutation_SUBTREE_ADD_CHILD
}

func (m *RGQLQueryTreeMutation_NodeMutation) GetNode() *RGQLQueryTreeNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type RGQLQueryFinish struct {
	// The ID of this query.
	QueryId              uint32   `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLQueryFinish) Reset()         { *m = RGQLQueryFinish{} }
func (m *RGQLQueryFinish) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryFinish) ProtoMessage()    {}
func (*RGQLQueryFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{8}
}

func (m *RGQLQueryFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryFinish.Unmarshal(m, b)
}
func (m *RGQLQueryFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryFinish.Marshal(b, m, deterministic)
}
func (m *RGQLQueryFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryFinish.Merge(m, src)
}
func (m *RGQLQueryFinish) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryFinish.Size(m)
}
func (m *RGQLQueryFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryFinish.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryFinish proto.InternalMessageInfo

func (m *RGQLQueryFinish) GetQueryId() uint32 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

type RGQLServerMessage struct {
	QueryError           *RGQLQueryError    `protobuf:"bytes,2,opt,name=query_error,json=queryError,proto3" json:"query_error,omitempty"`
	ValueInit            *RGQLValueInit     `protobuf:"bytes,4,opt,name=value_init,json=valueInit,proto3" json:"value_init,omitempty"`
	ValueBatch           *RGQLValueBatch    `protobuf:"bytes,5,opt,name=value_batch,json=valueBatch,proto3" json:"value_batch,omitempty"`
	ValueFinalize        *RGQLValueFinalize `protobuf:"bytes,6,opt,name=value_finalize,json=valueFinalize,proto3" json:"value_finalize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RGQLServerMessage) Reset()         { *m = RGQLServerMessage{} }
func (m *RGQLServerMessage) String() string { return proto.CompactTextString(m) }
func (*RGQLServerMessage) ProtoMessage()    {}
func (*RGQLServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{9}
}

func (m *RGQLServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLServerMessage.Unmarshal(m, b)
}
func (m *RGQLServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLServerMessage.Marshal(b, m, deterministic)
}
func (m *RGQLServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLServerMessage.Merge(m, src)
}
func (m *RGQLServerMessage) XXX_Size() int {
	return xxx_messageInfo_RGQLServerMessage.Size(m)
}
func (m *RGQLServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLServerMessage proto.InternalMessageInfo

func (m *RGQLServerMessage) GetQueryError() *RGQLQueryError {
	if m != nil {
		return m.QueryError
	}
	return nil
}

func (m *RGQLServerMessage) GetValueInit() *RGQLValueInit {
	if m != nil {
		return m.ValueInit
	}
	return nil
}

func (m *RGQLServerMessage) GetValueBatch() *RGQLValueBatch {
	if m != nil {
		return m.ValueBatch
	}
	return nil
}

func (m *RGQLServerMessage) GetValueFinalize() *RGQLValueFinalize {
	if m != nil {
		return m.ValueFinalize
	}
	return nil
}

// RGQLValueInit initializes a result value tree.
type RGQLValueInit struct {
	// result_id is the identifier for the result tree.
	ResultId uint32 `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	// query_id is the identifier for the corresponding query.
	QueryId uint32 `protobuf:"varint,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// cache_strategy is the strategy used for the path cache.
	CacheStrategy RGQLValueInit_CacheStrategy `protobuf:"varint,3,opt,name=cache_strategy,json=cacheStrategy,proto3,enum=rgraphql.RGQLValueInit_CacheStrategy" json:"cache_strategy,omitempty"`
	// cache_size is the size of the path cache, if necessary.
	CacheSize            uint32   `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLValueInit) Reset()         { *m = RGQLValueInit{} }
func (m *RGQLValueInit) String() string { return proto.CompactTextString(m) }
func (*RGQLValueInit) ProtoMessage()    {}
func (*RGQLValueInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{10}
}

func (m *RGQLValueInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLValueInit.Unmarshal(m, b)
}
func (m *RGQLValueInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLValueInit.Marshal(b, m, deterministic)
}
func (m *RGQLValueInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLValueInit.Merge(m, src)
}
func (m *RGQLValueInit) XXX_Size() int {
	return xxx_messageInfo_RGQLValueInit.Size(m)
}
func (m *RGQLValueInit) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLValueInit.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLValueInit proto.InternalMessageInfo

func (m *RGQLValueInit) GetResultId() uint32 {
	if m != nil {
		return m.ResultId
	}
	return 0
}

func (m *RGQLValueInit) GetQueryId() uint32 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *RGQLValueInit) GetCacheStrategy() RGQLValueInit_CacheStrategy {
	if m != nil {
		return m.CacheStrategy
	}
	return RGQLValueInit_CACHE_LRU
}

func (m *RGQLValueInit) GetCacheSize() uint32 {
	if m != nil {
		return m.CacheSize
	}
	return 0
}

// RGQLValueFinalize finalizes a result tree.
type RGQLValueFinalize struct {
	ResultId             uint32   `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLValueFinalize) Reset()         { *m = RGQLValueFinalize{} }
func (m *RGQLValueFinalize) String() string { return proto.CompactTextString(m) }
func (*RGQLValueFinalize) ProtoMessage()    {}
func (*RGQLValueFinalize) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{11}
}

func (m *RGQLValueFinalize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLValueFinalize.Unmarshal(m, b)
}
func (m *RGQLValueFinalize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLValueFinalize.Marshal(b, m, deterministic)
}
func (m *RGQLValueFinalize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLValueFinalize.Merge(m, src)
}
func (m *RGQLValueFinalize) XXX_Size() int {
	return xxx_messageInfo_RGQLValueFinalize.Size(m)
}
func (m *RGQLValueFinalize) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLValueFinalize.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLValueFinalize proto.InternalMessageInfo

func (m *RGQLValueFinalize) GetResultId() uint32 {
	if m != nil {
		return m.ResultId
	}
	return 0
}

// Communicating a failure in the input query.
type RGQLQueryError struct {
	QueryId              uint32   `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryNodeId          uint32   `protobuf:"varint,2,opt,name=query_node_id,json=queryNodeId,proto3" json:"query_node_id,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLQueryError) Reset()         { *m = RGQLQueryError{} }
func (m *RGQLQueryError) String() string { return proto.CompactTextString(m) }
func (*RGQLQueryError) ProtoMessage()    {}
func (*RGQLQueryError) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{12}
}

func (m *RGQLQueryError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLQueryError.Unmarshal(m, b)
}
func (m *RGQLQueryError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLQueryError.Marshal(b, m, deterministic)
}
func (m *RGQLQueryError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLQueryError.Merge(m, src)
}
func (m *RGQLQueryError) XXX_Size() int {
	return xxx_messageInfo_RGQLQueryError.Size(m)
}
func (m *RGQLQueryError) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLQueryError.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLQueryError proto.InternalMessageInfo

func (m *RGQLQueryError) GetQueryId() uint32 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *RGQLQueryError) GetQueryNodeId() uint32 {
	if m != nil {
		return m.QueryNodeId
	}
	return 0
}

func (m *RGQLQueryError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RGQLValue struct {
	// The ID of the field in the query tree, if a field.
	QueryNodeId uint32 `protobuf:"varint,1,opt,name=query_node_id,json=queryNodeId,proto3" json:"query_node_id,omitempty"`
	// The 1-based index, if an array element.
	ArrayIndex uint32 `protobuf:"varint,2,opt,name=array_index,json=arrayIndex,proto3" json:"array_index,omitempty"`
	// If this is a 0-th index value, this is a pointer to a previous identifier.
	// Otherwise, this is an identifier for adding an alias to this path.
	PosIdentifier uint32 `protobuf:"varint,3,opt,name=pos_identifier,json=posIdentifier,proto3" json:"pos_identifier,omitempty"`
	// The value, if we have one.
	Value *RGQLPrimitive `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// The error, if we are erroring this field.
	Error                string   `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLValue) Reset()         { *m = RGQLValue{} }
func (m *RGQLValue) String() string { return proto.CompactTextString(m) }
func (*RGQLValue) ProtoMessage()    {}
func (*RGQLValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{13}
}

func (m *RGQLValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLValue.Unmarshal(m, b)
}
func (m *RGQLValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLValue.Marshal(b, m, deterministic)
}
func (m *RGQLValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLValue.Merge(m, src)
}
func (m *RGQLValue) XXX_Size() int {
	return xxx_messageInfo_RGQLValue.Size(m)
}
func (m *RGQLValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLValue.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLValue proto.InternalMessageInfo

func (m *RGQLValue) GetQueryNodeId() uint32 {
	if m != nil {
		return m.QueryNodeId
	}
	return 0
}

func (m *RGQLValue) GetArrayIndex() uint32 {
	if m != nil {
		return m.ArrayIndex
	}
	return 0
}

func (m *RGQLValue) GetPosIdentifier() uint32 {
	if m != nil {
		return m.PosIdentifier
	}
	return 0
}

func (m *RGQLValue) GetValue() *RGQLPrimitive {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RGQLValue) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RGQLValueBatch struct {
	// The ID of the result tree this batch is for.
	ResultId uint32 `protobuf:"varint,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	// The batch of RGQLValue values, encoded.
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGQLValueBatch) Reset()         { *m = RGQLValueBatch{} }
func (m *RGQLValueBatch) String() string { return proto.CompactTextString(m) }
func (*RGQLValueBatch) ProtoMessage()    {}
func (*RGQLValueBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad052702e5fb13, []int{14}
}

func (m *RGQLValueBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGQLValueBatch.Unmarshal(m, b)
}
func (m *RGQLValueBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGQLValueBatch.Marshal(b, m, deterministic)
}
func (m *RGQLValueBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGQLValueBatch.Merge(m, src)
}
func (m *RGQLValueBatch) XXX_Size() int {
	return xxx_messageInfo_RGQLValueBatch.Size(m)
}
func (m *RGQLValueBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RGQLValueBatch.DiscardUnknown(m)
}

var xxx_messageInfo_RGQLValueBatch proto.InternalMessageInfo

func (m *RGQLValueBatch) GetResultId() uint32 {
	if m != nil {
		return m.ResultId
	}
	return 0
}

func (m *RGQLValueBatch) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("rgraphql.RGQLPrimitive_Kind", RGQLPrimitive_Kind_name, RGQLPrimitive_Kind_value)
	proto.RegisterEnum("rgraphql.RGQLQueryTreeMutation_SubtreeOperation", RGQLQueryTreeMutation_SubtreeOperation_name, RGQLQueryTreeMutation_SubtreeOperation_value)
	proto.RegisterEnum("rgraphql.RGQLValueInit_CacheStrategy", RGQLValueInit_CacheStrategy_name, RGQLValueInit_CacheStrategy_value)
	proto.RegisterType((*RGQLQueryFieldDirective)(nil), "rgraphql.RGQLQueryFieldDirective")
	proto.RegisterType((*RGQLQueryTreeNode)(nil), "rgraphql.RGQLQueryTreeNode")
	proto.RegisterType((*FieldArgument)(nil), "rgraphql.FieldArgument")
	proto.RegisterType((*ASTVariable)(nil), "rgraphql.ASTVariable")
	proto.RegisterType((*RGQLPrimitive)(nil), "rgraphql.RGQLPrimitive")
	proto.RegisterType((*RGQLClientMessage)(nil), "rgraphql.RGQLClientMessage")
	proto.RegisterType((*RGQLQueryInit)(nil), "rgraphql.RGQLQueryInit")
	proto.RegisterType((*RGQLQueryTreeMutation)(nil), "rgraphql.RGQLQueryTreeMutation")
	proto.RegisterType((*RGQLQueryTreeMutation_NodeMutation)(nil), "rgraphql.RGQLQueryTreeMutation.NodeMutation")
	proto.RegisterType((*RGQLQueryFinish)(nil), "rgraphql.RGQLQueryFinish")
	proto.RegisterType((*RGQLServerMessage)(nil), "rgraphql.RGQLServerMessage")
	proto.RegisterType((*RGQLValueInit)(nil), "rgraphql.RGQLValueInit")
	proto.RegisterType((*RGQLValueFinalize)(nil), "rgraphql.RGQLValueFinalize")
	proto.RegisterType((*RGQLQueryError)(nil), "rgraphql.RGQLQueryError")
	proto.RegisterType((*RGQLValue)(nil), "rgraphql.RGQLValue")
	proto.RegisterType((*RGQLValueBatch)(nil), "rgraphql.RGQLValueBatch")
}

func init() {
	proto.RegisterFile("github.com/rgraphql/rgraphql/rgraphql.proto", fileDescriptor_5cad052702e5fb13)
}

var fileDescriptor_5cad052702e5fb13 = []byte{
	// 1081 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x75, 0x70, 0xc4, 0x91, 0xa9, 0x9f, 0xd9, 0x3f, 0x8e, 0xe5, 0xa6, 0xa9, 0x1d, 0x02,
	0x01, 0x0c, 0x24, 0x55, 0x0c, 0x07, 0x68, 0x51, 0xa0, 0x45, 0x2b, 0x4b, 0x72, 0xc2, 0x46, 0x96,
	0xe3, 0x95, 0x6c, 0xa0, 0xbd, 0x21, 0x28, 0x71, 0x25, 0x2d, 0x4a, 0x91, 0xf2, 0x8a, 0x12, 0xea,
	0xde, 0xf7, 0x4d, 0x7a, 0xd1, 0x67, 0x28, 0xfa, 0x06, 0xbd, 0xed, 0x4b, 0xf4, 0x25, 0x8a, 0x62,
	0x67, 0x49, 0x4a, 0xb2, 0x64, 0x25, 0x77, 0x3b, 0xb3, 0xdf, 0x37, 0xa7, 0x9d, 0x19, 0x12, 0x5e,
	0x0c, 0x78, 0x34, 0x9c, 0x76, 0x2b, 0xbd, 0x70, 0xf4, 0x4a, 0x0c, 0x84, 0x3b, 0x1e, 0xde, 0xf8,
	0xab, 0x87, 0xca, 0x58, 0x84, 0x51, 0x48, 0x0a, 0x89, 0x6c, 0xfd, 0x08, 0x7b, 0xf4, 0xcd, 0x65,
	0xf3, 0x72, 0xca, 0xc4, 0xed, 0x19, 0x67, 0xbe, 0x57, 0xe7, 0x82, 0xf5, 0x22, 0x3e, 0x63, 0x84,
	0x40, 0x2e, 0x70, 0x47, 0xac, 0xac, 0x1d, 0x6a, 0x47, 0x3a, 0xc5, 0x33, 0x79, 0x01, 0x39, 0x57,
	0x0c, 0x26, 0xe5, 0xcc, 0x61, 0xf6, 0xa8, 0x78, 0xb2, 0x57, 0x49, 0xed, 0x22, 0xb7, 0x2a, 0x06,
	0xd3, 0x11, 0x0b, 0x22, 0x8a, 0x20, 0xeb, 0x1f, 0x0d, 0x1e, 0xa6, 0xc6, 0x3b, 0x82, 0xb1, 0x56,
	0xe8, 0x31, 0x52, 0x82, 0x0c, 0xf7, 0xd0, 0xa8, 0x41, 0x33, 0xdc, 0x23, 0x4f, 0x01, 0xfa, 0x92,
	0xec, 0xa0, 0xb3, 0x0c, 0x3a, 0xd3, 0x51, 0xd3, 0x5a, 0xf4, 0x98, 0xfd, 0x08, 0x8f, 0xe4, 0x5b,
	0xd0, 0xbd, 0x24, 0xfe, 0x72, 0x0e, 0x19, 0xcf, 0xe6, 0x8c, 0x7b, 0x12, 0xa5, 0x73, 0x0e, 0xf9,
	0x12, 0x0a, 0xbd, 0x21, 0xf7, 0x3d, 0xc1, 0x82, 0x72, 0x1e, 0xf9, 0x4f, 0xd6, 0xf0, 0x93, 0x5c,
	0x68, 0x0a, 0xb6, 0xea, 0x60, 0x2c, 0x05, 0xb4, 0xb6, 0x7a, 0x07, 0x50, 0x9c, 0xb9, 0x82, 0xbb,
	0x5d, 0x9f, 0x39, 0xdc, 0xc3, 0x5c, 0x0d, 0x0a, 0x89, 0xca, 0xf6, 0xac, 0x26, 0x14, 0xab, 0xed,
	0xce, 0x75, 0xac, 0x58, 0x29, 0xd5, 0xe7, 0x90, 0x9f, 0xb9, 0xfe, 0x54, 0x55, 0x69, 0xa9, 0x18,
	0x32, 0xb4, 0xf7, 0x82, 0x8f, 0x38, 0x26, 0xa4, 0x50, 0xd6, 0xbf, 0x19, 0x30, 0x96, 0x2e, 0xc8,
	0x31, 0xe4, 0x7e, 0xe2, 0x81, 0x32, 0x59, 0x3a, 0xf9, 0xf4, 0x1e, 0x7e, 0xe5, 0x1d, 0x0f, 0x3c,
	0x8a, 0x48, 0xf2, 0x04, 0x74, 0x1e, 0x44, 0xce, 0xdc, 0x6d, 0x9e, 0x16, 0x78, 0x10, 0x5d, 0x4b,
	0x59, 0xe6, 0xd3, 0xf7, 0x43, 0x37, 0xb9, 0xce, 0x1e, 0x6a, 0x47, 0x1a, 0x05, 0x54, 0x29, 0xc0,
	0x33, 0xd8, 0x99, 0x44, 0x82, 0x07, 0x83, 0x18, 0x91, 0xc3, 0x62, 0x14, 0x95, 0x4e, 0x41, 0x9e,
	0x02, 0x74, 0xc3, 0xd0, 0x8f, 0x01, 0xf9, 0x43, 0xed, 0xa8, 0x40, 0x75, 0xa9, 0xc1, 0x6b, 0xeb,
	0x0f, 0x0d, 0x72, 0x32, 0x1c, 0xb2, 0x07, 0xff, 0x7f, 0x4f, 0xed, 0x73, 0xbb, 0x63, 0x5f, 0x37,
	0x9c, 0x77, 0x76, 0xab, 0xee, 0xb4, 0xae, 0x9a, 0x4d, 0x73, 0x8b, 0x3c, 0x06, 0x72, 0xe7, 0xc2,
	0x6e, 0x75, 0x4c, 0x8d, 0x94, 0xe1, 0xd1, 0x1d, 0xfd, 0x59, 0xf3, 0xa2, 0xda, 0x31, 0x33, 0x64,
	0x1f, 0x76, 0xef, 0xdc, 0xb4, 0x3b, 0xd4, 0x6e, 0xbd, 0x31, 0xb3, 0x6b, 0xbc, 0x9c, 0x5e, 0x5c,
	0x34, 0xcd, 0xdc, 0x1a, 0xce, 0xc5, 0xe9, 0xf7, 0x8d, 0x5a, 0xc7, 0xcc, 0xaf, 0x71, 0x54, 0xa5,
	0xb4, 0xfa, 0x83, 0xb9, 0x6d, 0xfd, 0x15, 0x0f, 0x40, 0xcd, 0xe7, 0x2c, 0x88, 0xce, 0xd9, 0x64,
	0xe2, 0x0e, 0x18, 0xf9, 0x02, 0x80, 0x07, 0x3c, 0x72, 0x6e, 0x64, 0x2b, 0xe1, 0x53, 0xac, 0x3c,
	0x25, 0x76, 0x99, 0x1d, 0xf0, 0x88, 0xea, 0x12, 0x8a, 0x22, 0xf9, 0x0e, 0x8a, 0xa3, 0x69, 0xe4,
	0x46, 0xcc, 0x89, 0x04, 0x4b, 0x7a, 0xe0, 0xe0, 0x9e, 0xf6, 0x3c, 0x97, 0x48, 0x1e, 0x06, 0x14,
	0x14, 0x47, 0xea, 0xc8, 0xd7, 0xb0, 0xd3, 0xe7, 0x01, 0x9f, 0x0c, 0x63, 0xdf, 0x59, 0x34, 0xb1,
	0xbf, 0x76, 0x42, 0x24, 0x8c, 0x16, 0x15, 0x1c, 0x55, 0x56, 0xa4, 0xba, 0x29, 0x8d, 0x8d, 0xec,
	0x43, 0x01, 0xed, 0x38, 0x69, 0x93, 0x3e, 0x40, 0xd9, 0xf6, 0xe4, 0xc3, 0xf7, 0x43, 0xd1, 0x63,
	0xce, 0x84, 0x09, 0xee, 0xfa, 0x18, 0x6c, 0x81, 0x16, 0x51, 0xd7, 0x46, 0x15, 0x79, 0x0e, 0xa5,
	0x70, 0xcc, 0x04, 0x46, 0xe9, 0x44, 0xb7, 0x63, 0xd5, 0x3f, 0x3a, 0x35, 0x52, 0x6d, 0xe7, 0x76,
	0xcc, 0xac, 0xdf, 0xb2, 0xb0, 0xbb, 0x36, 0xb3, 0x4d, 0xee, 0x2f, 0xc1, 0x08, 0x42, 0x8f, 0x39,
	0xa3, 0x18, 0x1b, 0xef, 0xab, 0x97, 0x1f, 0x28, 0x56, 0x45, 0x0e, 0x75, 0x5a, 0xb9, 0x9d, 0x60,
	0x41, 0x22, 0xaf, 0x41, 0x4f, 0x06, 0x35, 0x59, 0x46, 0xbb, 0x73, 0x73, 0x0b, 0x53, 0x4b, 0xe7,
	0xb8, 0x4f, 0x7e, 0xd7, 0x60, 0x67, 0xd1, 0x26, 0xd9, 0x83, 0x07, 0x18, 0x58, 0x1a, 0xf2, 0xb6,
	0x14, 0x6d, 0x8f, 0xb4, 0x40, 0x4f, 0xf3, 0xc6, 0x6a, 0x95, 0x4e, 0x8e, 0x3f, 0x14, 0x6d, 0x7b,
	0xda, 0x95, 0x9d, 0x70, 0x91, 0xf0, 0xe8, 0xdc, 0x04, 0x79, 0x05, 0x39, 0x69, 0x39, 0x7e, 0xe2,
	0x8d, 0x4b, 0x0c, 0x81, 0xd6, 0x37, 0x60, 0xde, 0xb5, 0x47, 0x76, 0xe1, 0x61, 0xfb, 0xea, 0xb4,
	0x43, 0x1b, 0x0d, 0xa7, 0x5a, 0xaf, 0x3b, 0xb5, 0xb7, 0x76, 0xb3, 0x6e, 0x6e, 0x11, 0x02, 0xa5,
	0x44, 0x5d, 0x6f, 0x34, 0x1b, 0x9d, 0x86, 0xa9, 0x59, 0x2f, 0xe1, 0x7f, 0x77, 0x9a, 0x67, 0xc3,
	0xfb, 0x58, 0xbf, 0x66, 0xd4, 0x60, 0xb4, 0x99, 0x98, 0x31, 0x91, 0x0c, 0xc6, 0x57, 0x50, 0x54,
	0x04, 0x26, 0x44, 0x28, 0xe2, 0x06, 0x2f, 0xaf, 0x09, 0xbd, 0x21, 0xef, 0x29, 0xdc, 0xa4, 0x67,
	0x39, 0x53, 0xb8, 0x40, 0x1c, 0x39, 0x2e, 0xb8, 0x66, 0x56, 0x66, 0x0a, 0xf7, 0x89, 0x9a, 0xa9,
	0x59, 0x72, 0x94, 0x2e, 0x15, 0xaf, 0xeb, 0x46, 0xbd, 0x21, 0xae, 0x9f, 0x15, 0x97, 0x48, 0x3c,
	0x95, 0xf7, 0x54, 0x39, 0xc1, 0x33, 0x39, 0x85, 0x92, 0xa2, 0xf6, 0x79, 0xe0, 0xfa, 0xfc, 0x17,
	0x56, 0xde, 0x5e, 0x57, 0x6b, 0x64, 0x9f, 0xc5, 0x10, 0x6a, 0xcc, 0x16, 0x45, 0xeb, 0x6f, 0x4d,
	0xcd, 0x54, 0x1a, 0x9b, 0xdc, 0xb7, 0x82, 0x4d, 0xa6, 0x7e, 0x34, 0xaf, 0x5a, 0x41, 0x29, 0x6c,
	0x6f, 0xa9, 0xa2, 0x99, 0xe5, 0x8e, 0x6f, 0x42, 0xa9, 0xe7, 0xf6, 0x86, 0xcc, 0x99, 0x44, 0xc2,
	0x8d, 0xd8, 0x40, 0x0d, 0x77, 0xe9, 0xe4, 0xf9, 0x3d, 0x45, 0xa8, 0xd4, 0x24, 0xba, 0x1d, 0x83,
	0xa9, 0xd1, 0x5b, 0x14, 0xe5, 0x52, 0x8e, 0xad, 0xc9, 0xbc, 0x72, 0xe8, 0x4a, 0x57, 0x10, 0x19,
	0xf6, 0x67, 0x60, 0x2c, 0xd1, 0x89, 0x01, 0x7a, 0xad, 0x5a, 0x7b, 0xdb, 0x70, 0x9a, 0xf4, 0xca,
	0xdc, 0xb2, 0x8e, 0xd5, 0xeb, 0x2e, 0xa5, 0xbe, 0x31, 0x33, 0x8b, 0x41, 0x69, 0xf9, 0x75, 0x37,
	0x4d, 0xb7, 0x05, 0x86, 0xba, 0x4a, 0x46, 0x49, 0xd5, 0x42, 0x35, 0x4f, 0x4b, 0xcd, 0xd3, 0x23,
	0xc8, 0xab, 0x2e, 0x52, 0x4b, 0x45, 0x09, 0xd6, 0x9f, 0x1a, 0xe8, 0x69, 0x64, 0xab, 0x76, 0xb4,
	0x55, 0x3b, 0x07, 0x50, 0x74, 0x85, 0x70, 0x6f, 0x1d, 0x1e, 0x78, 0xec, 0xe7, 0xe4, 0x93, 0x8d,
	0x2a, 0x5b, 0x6a, 0xe4, 0x1a, 0x1b, 0x87, 0x13, 0x87, 0x7b, 0x2c, 0x88, 0x78, 0x9f, 0x33, 0xe5,
	0xd1, 0xa0, 0xc6, 0x38, 0x9c, 0xd8, 0xa9, 0x72, 0xfe, 0xe9, 0xce, 0x7d, 0xcc, 0xa7, 0x7b, 0x1e,
	0x7e, 0x7e, 0x31, 0xfc, 0x86, 0xaa, 0xd2, 0xbc, 0x21, 0x37, 0xb7, 0xcb, 0x63, 0xd8, 0x46, 0x6b,
	0xea, 0x77, 0x6d, 0x87, 0xc6, 0x52, 0x77, 0x1b, 0x7f, 0x02, 0x5f, 0xff, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x07, 0x65, 0x8c, 0x7d, 0x33, 0x0a, 0x00, 0x00,
}
