// Code generated by protoc-gen-go.
// source: src/rgraphql.proto
// DO NOT EDIT!

/*
Package rgraphql is a generated protocol buffer package.

It is generated from these files:
	src/rgraphql.proto

It has these top-level messages:
	RGQLQueryFieldDirective
	RGQLQueryTreeNode
	FieldArgument
	ASTVariable
	RGQLClientMessage
	RGQLTreeMutation
	RGQLServerMessage
	RGQLQueryError
	RGQLValueMutation
*/
package rgraphql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RGQLTreeMutation_SubtreeOperation int32

const (
	// Add a child tree to the subtree.
	RGQLTreeMutation_SUBTREE_ADD_CHILD RGQLTreeMutation_SubtreeOperation = 0
	// Delete a tree node and all children.
	RGQLTreeMutation_SUBTREE_DELETE RGQLTreeMutation_SubtreeOperation = 1
)

var RGQLTreeMutation_SubtreeOperation_name = map[int32]string{
	0: "SUBTREE_ADD_CHILD",
	1: "SUBTREE_DELETE",
}
var RGQLTreeMutation_SubtreeOperation_value = map[string]int32{
	"SUBTREE_ADD_CHILD": 0,
	"SUBTREE_DELETE":    1,
}

func (x RGQLTreeMutation_SubtreeOperation) String() string {
	return proto.EnumName(RGQLTreeMutation_SubtreeOperation_name, int32(x))
}
func (RGQLTreeMutation_SubtreeOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type RGQLValueMutation_ValueOperation int32

const (
	// Set/create the value of this resolver.
	RGQLValueMutation_VALUE_SET RGQLValueMutation_ValueOperation = 0
	// Error this resolver (the value will enter the errored state).
	RGQLValueMutation_VALUE_ERROR RGQLValueMutation_ValueOperation = 1
	// Delete this resolver
	RGQLValueMutation_VALUE_DELETE RGQLValueMutation_ValueOperation = 2
)

var RGQLValueMutation_ValueOperation_name = map[int32]string{
	0: "VALUE_SET",
	1: "VALUE_ERROR",
	2: "VALUE_DELETE",
}
var RGQLValueMutation_ValueOperation_value = map[string]int32{
	"VALUE_SET":    0,
	"VALUE_ERROR":  1,
	"VALUE_DELETE": 2,
}

func (x RGQLValueMutation_ValueOperation) String() string {
	return proto.EnumName(RGQLValueMutation_ValueOperation_name, int32(x))
}
func (RGQLValueMutation_ValueOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

type RGQLQueryFieldDirective struct {
	// Directive name
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Optional arguments.
	Args []*FieldArgument `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *RGQLQueryFieldDirective) Reset()                    { *m = RGQLQueryFieldDirective{} }
func (m *RGQLQueryFieldDirective) String() string            { return proto.CompactTextString(m) }
func (*RGQLQueryFieldDirective) ProtoMessage()               {}
func (*RGQLQueryFieldDirective) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RGQLQueryFieldDirective) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RGQLQueryFieldDirective) GetArgs() []*FieldArgument {
	if m != nil {
		return m.Args
	}
	return nil
}

type RGQLQueryTreeNode struct {
	// Integer ID of the node.
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Name of the field this node represents.
	FieldName string `protobuf:"bytes,2,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	// Arguments.
	Args []*FieldArgument `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	// Directives
	Directive []*RGQLQueryFieldDirective `protobuf:"bytes,4,rep,name=directive" json:"directive,omitempty"`
	// Children
	Children []*RGQLQueryTreeNode `protobuf:"bytes,5,rep,name=children" json:"children,omitempty"`
}

func (m *RGQLQueryTreeNode) Reset()                    { *m = RGQLQueryTreeNode{} }
func (m *RGQLQueryTreeNode) String() string            { return proto.CompactTextString(m) }
func (*RGQLQueryTreeNode) ProtoMessage()               {}
func (*RGQLQueryTreeNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RGQLQueryTreeNode) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RGQLQueryTreeNode) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *RGQLQueryTreeNode) GetArgs() []*FieldArgument {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *RGQLQueryTreeNode) GetDirective() []*RGQLQueryFieldDirective {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *RGQLQueryTreeNode) GetChildren() []*RGQLQueryTreeNode {
	if m != nil {
		return m.Children
	}
	return nil
}

type FieldArgument struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	VariableId uint32 `protobuf:"varint,2,opt,name=variable_id,json=variableId" json:"variable_id,omitempty"`
}

func (m *FieldArgument) Reset()                    { *m = FieldArgument{} }
func (m *FieldArgument) String() string            { return proto.CompactTextString(m) }
func (*FieldArgument) ProtoMessage()               {}
func (*FieldArgument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FieldArgument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldArgument) GetVariableId() uint32 {
	if m != nil {
		return m.VariableId
	}
	return 0
}

type ASTVariable struct {
	Id        uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	JsonValue string `protobuf:"bytes,2,opt,name=json_value,json=jsonValue" json:"json_value,omitempty"`
}

func (m *ASTVariable) Reset()                    { *m = ASTVariable{} }
func (m *ASTVariable) String() string            { return proto.CompactTextString(m) }
func (*ASTVariable) ProtoMessage()               {}
func (*ASTVariable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ASTVariable) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ASTVariable) GetJsonValue() string {
	if m != nil {
		return m.JsonValue
	}
	return ""
}

// Messages
type RGQLClientMessage struct {
	MutateTree *RGQLTreeMutation `protobuf:"bytes,1,opt,name=mutate_tree,json=mutateTree" json:"mutate_tree,omitempty"`
}

func (m *RGQLClientMessage) Reset()                    { *m = RGQLClientMessage{} }
func (m *RGQLClientMessage) String() string            { return proto.CompactTextString(m) }
func (*RGQLClientMessage) ProtoMessage()               {}
func (*RGQLClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RGQLClientMessage) GetMutateTree() *RGQLTreeMutation {
	if m != nil {
		return m.MutateTree
	}
	return nil
}

type RGQLTreeMutation struct {
	// All node mutations in this step.
	NodeMutation []*RGQLTreeMutation_NodeMutation `protobuf:"bytes,1,rep,name=node_mutation,json=nodeMutation" json:"node_mutation,omitempty"`
	// Any new variables.
	Variables []*ASTVariable `protobuf:"bytes,2,rep,name=variables" json:"variables,omitempty"`
}

func (m *RGQLTreeMutation) Reset()                    { *m = RGQLTreeMutation{} }
func (m *RGQLTreeMutation) String() string            { return proto.CompactTextString(m) }
func (*RGQLTreeMutation) ProtoMessage()               {}
func (*RGQLTreeMutation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RGQLTreeMutation) GetNodeMutation() []*RGQLTreeMutation_NodeMutation {
	if m != nil {
		return m.NodeMutation
	}
	return nil
}

func (m *RGQLTreeMutation) GetVariables() []*ASTVariable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type RGQLTreeMutation_NodeMutation struct {
	// ID of the node we are operating on.
	NodeId uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	// Operation we are taking.
	Operation RGQLTreeMutation_SubtreeOperation `protobuf:"varint,2,opt,name=operation,enum=rgraphql.RGQLTreeMutation_SubtreeOperation" json:"operation,omitempty"`
	// The new node tree to add, if we are adding a child.
	Node *RGQLQueryTreeNode `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
}

func (m *RGQLTreeMutation_NodeMutation) Reset()         { *m = RGQLTreeMutation_NodeMutation{} }
func (m *RGQLTreeMutation_NodeMutation) String() string { return proto.CompactTextString(m) }
func (*RGQLTreeMutation_NodeMutation) ProtoMessage()    {}
func (*RGQLTreeMutation_NodeMutation) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *RGQLTreeMutation_NodeMutation) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *RGQLTreeMutation_NodeMutation) GetOperation() RGQLTreeMutation_SubtreeOperation {
	if m != nil {
		return m.Operation
	}
	return RGQLTreeMutation_SUBTREE_ADD_CHILD
}

func (m *RGQLTreeMutation_NodeMutation) GetNode() *RGQLQueryTreeNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type RGQLServerMessage struct {
	MutateValue *RGQLValueMutation `protobuf:"bytes,1,opt,name=mutate_value,json=mutateValue" json:"mutate_value,omitempty"`
	QueryError  *RGQLQueryError    `protobuf:"bytes,2,opt,name=query_error,json=queryError" json:"query_error,omitempty"`
}

func (m *RGQLServerMessage) Reset()                    { *m = RGQLServerMessage{} }
func (m *RGQLServerMessage) String() string            { return proto.CompactTextString(m) }
func (*RGQLServerMessage) ProtoMessage()               {}
func (*RGQLServerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RGQLServerMessage) GetMutateValue() *RGQLValueMutation {
	if m != nil {
		return m.MutateValue
	}
	return nil
}

func (m *RGQLServerMessage) GetQueryError() *RGQLQueryError {
	if m != nil {
		return m.QueryError
	}
	return nil
}

// Communicating a failure in the input query.
type RGQLQueryError struct {
	QueryNodeId uint32 `protobuf:"varint,1,opt,name=query_node_id,json=queryNodeId" json:"query_node_id,omitempty"`
	ErrorJson   string `protobuf:"bytes,2,opt,name=error_json,json=errorJson" json:"error_json,omitempty"`
}

func (m *RGQLQueryError) Reset()                    { *m = RGQLQueryError{} }
func (m *RGQLQueryError) String() string            { return proto.CompactTextString(m) }
func (*RGQLQueryError) ProtoMessage()               {}
func (*RGQLQueryError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RGQLQueryError) GetQueryNodeId() uint32 {
	if m != nil {
		return m.QueryNodeId
	}
	return 0
}

func (m *RGQLQueryError) GetErrorJson() string {
	if m != nil {
		return m.ErrorJson
	}
	return ""
}

type RGQLValueMutation struct {
	// The ID of the resolver execution (the value identifier).
	ValueNodeId uint32 `protobuf:"varint,1,opt,name=value_node_id,json=valueNodeId" json:"value_node_id,omitempty"`
	// The ID of the parent resolver execution (the parent value identifier).
	ParentValueNodeId uint32 `protobuf:"varint,2,opt,name=parent_value_node_id,json=parentValueNodeId" json:"parent_value_node_id,omitempty"`
	// The ID of the query node (the query identifier).
	QueryNodeId uint32 `protobuf:"varint,3,opt,name=query_node_id,json=queryNodeId" json:"query_node_id,omitempty"`
	// The operation on the value.
	Operation RGQLValueMutation_ValueOperation `protobuf:"varint,4,opt,name=operation,enum=rgraphql.RGQLValueMutation_ValueOperation" json:"operation,omitempty"`
	// The actual value itself
	ValueJson string `protobuf:"bytes,5,opt,name=value_json,json=valueJson" json:"value_json,omitempty"`
	// Do we have a value to set?
	HasValue bool `protobuf:"varint,6,opt,name=has_value,json=hasValue" json:"has_value,omitempty"`
	// Is this a marker for an array?
	IsArray bool `protobuf:"varint,7,opt,name=is_array,json=isArray" json:"is_array,omitempty"`
}

func (m *RGQLValueMutation) Reset()                    { *m = RGQLValueMutation{} }
func (m *RGQLValueMutation) String() string            { return proto.CompactTextString(m) }
func (*RGQLValueMutation) ProtoMessage()               {}
func (*RGQLValueMutation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RGQLValueMutation) GetValueNodeId() uint32 {
	if m != nil {
		return m.ValueNodeId
	}
	return 0
}

func (m *RGQLValueMutation) GetParentValueNodeId() uint32 {
	if m != nil {
		return m.ParentValueNodeId
	}
	return 0
}

func (m *RGQLValueMutation) GetQueryNodeId() uint32 {
	if m != nil {
		return m.QueryNodeId
	}
	return 0
}

func (m *RGQLValueMutation) GetOperation() RGQLValueMutation_ValueOperation {
	if m != nil {
		return m.Operation
	}
	return RGQLValueMutation_VALUE_SET
}

func (m *RGQLValueMutation) GetValueJson() string {
	if m != nil {
		return m.ValueJson
	}
	return ""
}

func (m *RGQLValueMutation) GetHasValue() bool {
	if m != nil {
		return m.HasValue
	}
	return false
}

func (m *RGQLValueMutation) GetIsArray() bool {
	if m != nil {
		return m.IsArray
	}
	return false
}

func init() {
	proto.RegisterType((*RGQLQueryFieldDirective)(nil), "rgraphql.RGQLQueryFieldDirective")
	proto.RegisterType((*RGQLQueryTreeNode)(nil), "rgraphql.RGQLQueryTreeNode")
	proto.RegisterType((*FieldArgument)(nil), "rgraphql.FieldArgument")
	proto.RegisterType((*ASTVariable)(nil), "rgraphql.ASTVariable")
	proto.RegisterType((*RGQLClientMessage)(nil), "rgraphql.RGQLClientMessage")
	proto.RegisterType((*RGQLTreeMutation)(nil), "rgraphql.RGQLTreeMutation")
	proto.RegisterType((*RGQLTreeMutation_NodeMutation)(nil), "rgraphql.RGQLTreeMutation.NodeMutation")
	proto.RegisterType((*RGQLServerMessage)(nil), "rgraphql.RGQLServerMessage")
	proto.RegisterType((*RGQLQueryError)(nil), "rgraphql.RGQLQueryError")
	proto.RegisterType((*RGQLValueMutation)(nil), "rgraphql.RGQLValueMutation")
	proto.RegisterEnum("rgraphql.RGQLTreeMutation_SubtreeOperation", RGQLTreeMutation_SubtreeOperation_name, RGQLTreeMutation_SubtreeOperation_value)
	proto.RegisterEnum("rgraphql.RGQLValueMutation_ValueOperation", RGQLValueMutation_ValueOperation_name, RGQLValueMutation_ValueOperation_value)
}

func init() { proto.RegisterFile("src/rgraphql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0xc5, 0x4e, 0x80, 0x78, 0x9c, 0xa4, 0x66, 0x55, 0x84, 0x0b, 0x42, 0xa5, 0xbe, 0x14, 0x15,
	0x29, 0x48, 0xe1, 0x50, 0x55, 0xfd, 0x52, 0x20, 0x6e, 0x49, 0x15, 0xa0, 0x6c, 0x42, 0x0e, 0xbd,
	0x58, 0x06, 0x6f, 0x13, 0x57, 0x89, 0x1d, 0xd6, 0x4e, 0x24, 0xfe, 0x44, 0xff, 0x44, 0x7f, 0x5d,
	0x8f, 0xbd, 0xf6, 0x54, 0xed, 0xac, 0xed, 0xc4, 0x10, 0xa2, 0xde, 0xb2, 0x6f, 0x67, 0xde, 0xbc,
	0x79, 0xfb, 0xac, 0x00, 0x89, 0xf8, 0xcd, 0x21, 0xef, 0x73, 0x77, 0x3c, 0xb8, 0x1d, 0xd6, 0xc6,
	0x3c, 0x8c, 0x43, 0x52, 0x4a, 0xcf, 0xd6, 0x37, 0xd8, 0xa2, 0x9f, 0x2f, 0xdb, 0x97, 0x13, 0xc6,
	0xef, 0x3e, 0xf9, 0x6c, 0xe8, 0x35, 0x7d, 0xce, 0x6e, 0x62, 0x7f, 0xca, 0x08, 0x81, 0x62, 0xe0,
	0x8e, 0x98, 0xa9, 0xec, 0x29, 0xfb, 0x1a, 0xc5, 0xdf, 0xe4, 0x00, 0x8a, 0x2e, 0xef, 0x47, 0xa6,
	0xba, 0x57, 0xd8, 0xd7, 0xeb, 0x5b, 0xb5, 0x8c, 0x17, 0x7b, 0x1b, 0xbc, 0x3f, 0x19, 0xb1, 0x20,
	0xa6, 0x58, 0x64, 0xfd, 0x56, 0x60, 0x23, 0x23, 0xef, 0x72, 0xc6, 0xce, 0x43, 0x8f, 0x91, 0x2a,
	0xa8, 0xbe, 0x87, 0xa4, 0x15, 0xaa, 0xfa, 0x1e, 0xd9, 0x05, 0xf8, 0x2e, 0x9a, 0x1d, 0x1c, 0xa6,
	0xe2, 0x30, 0x0d, 0x91, 0xf3, 0xf9, 0x89, 0x85, 0xff, 0x98, 0x48, 0x3e, 0x82, 0xe6, 0xa5, 0xfa,
	0xcd, 0x22, 0x76, 0xbc, 0x98, 0x75, 0x3c, 0xb2, 0x28, 0x9d, 0xf5, 0x90, 0xd7, 0x50, 0xba, 0x19,
	0xf8, 0x43, 0x8f, 0xb3, 0xc0, 0x5c, 0xc5, 0xfe, 0x9d, 0x05, 0xfd, 0xe9, 0x2e, 0x34, 0x2b, 0xb6,
	0x9a, 0x50, 0xc9, 0x09, 0x5a, 0xe8, 0xde, 0x73, 0xd0, 0xa7, 0x2e, 0xf7, 0xdd, 0xeb, 0x21, 0x73,
	0x7c, 0x0f, 0x77, 0xad, 0x50, 0x48, 0xa1, 0x96, 0x67, 0xbd, 0x03, 0xbd, 0xd1, 0xe9, 0xf6, 0x12,
	0x60, 0x91, 0x55, 0x3f, 0xa2, 0x30, 0x70, 0xa6, 0xee, 0x70, 0x92, 0x59, 0x25, 0x90, 0x9e, 0x00,
	0xac, 0xaf, 0xd2, 0xee, 0x93, 0xa1, 0xcf, 0x82, 0xf8, 0x8c, 0x45, 0x91, 0xdb, 0x67, 0xe4, 0x2d,
	0xe8, 0xa3, 0x49, 0xec, 0xc6, 0xcc, 0x89, 0x39, 0x93, 0x72, 0xf4, 0xfa, 0x76, 0x7e, 0x29, 0xb1,
	0xcf, 0x99, 0x28, 0xf2, 0xc3, 0x80, 0x82, 0x2c, 0x17, 0x98, 0xf5, 0x57, 0x05, 0xe3, 0x7e, 0x01,
	0x69, 0x43, 0x25, 0x08, 0x3d, 0xe6, 0x8c, 0x12, 0xc0, 0x54, 0xd0, 0xa8, 0x97, 0x8f, 0x73, 0xd6,
	0x84, 0x59, 0xd9, 0x80, 0x72, 0x30, 0x77, 0x22, 0x47, 0xa0, 0xa5, 0x06, 0xa4, 0xb1, 0xda, 0x9c,
	0x31, 0xcd, 0xb9, 0x41, 0x67, 0x75, 0xdb, 0xbf, 0x14, 0x28, 0xcf, 0x73, 0x92, 0x2d, 0x58, 0x47,
	0x4d, 0x99, 0x5d, 0x6b, 0xe2, 0xd8, 0xf2, 0x48, 0x0b, 0xb4, 0x70, 0xcc, 0xb8, 0x14, 0x2a, 0x1c,
	0xab, 0xd6, 0x0f, 0x96, 0x08, 0xed, 0x4c, 0xae, 0x85, 0x4d, 0x17, 0x69, 0x0b, 0x9d, 0x75, 0x93,
	0x43, 0x28, 0x0a, 0x52, 0xb3, 0x80, 0x16, 0x2e, 0xcd, 0x05, 0x16, 0x5a, 0xef, 0xc1, 0xb8, 0xcf,
	0x47, 0x36, 0x61, 0xa3, 0x73, 0x75, 0xdc, 0xa5, 0xb6, 0xed, 0x34, 0x9a, 0x4d, 0xe7, 0xe4, 0xb4,
	0xd5, 0x6e, 0x1a, 0x2b, 0x84, 0x40, 0x35, 0x85, 0x9b, 0x76, 0xdb, 0xee, 0xda, 0x86, 0x62, 0xfd,
	0x4c, 0x3e, 0x9f, 0x0e, 0xe3, 0x53, 0xc6, 0xd3, 0xf7, 0xfc, 0x00, 0xe5, 0xe4, 0x3d, 0x65, 0x0a,
	0x94, 0x45, 0x6a, 0x30, 0x0f, 0x99, 0xe1, 0x49, 0x00, 0x10, 0x24, 0x6f, 0x40, 0xbf, 0x15, 0x5a,
	0x1d, 0xc6, 0x79, 0xc8, 0xd1, 0x12, 0xbd, 0x6e, 0x2e, 0x58, 0xc6, 0x16, 0xf7, 0x14, 0x6e, 0xb3,
	0xdf, 0x56, 0x07, 0xaa, 0xf9, 0x5b, 0x62, 0x41, 0x45, 0x92, 0xe5, 0xcd, 0x97, 0x13, 0xce, 0xe5,
	0x0b, 0xec, 0x02, 0xe0, 0x28, 0x47, 0x04, 0x35, 0x0d, 0x2d, 0x22, 0x5f, 0xa2, 0x30, 0xb0, 0xfe,
	0xa8, 0x72, 0xcb, 0x9c, 0x64, 0x41, 0x8c, 0xeb, 0xdd, 0x27, 0x46, 0x30, 0x21, 0x3e, 0x84, 0xa7,
	0x63, 0x97, 0xb3, 0x20, 0x76, 0xf2, 0xa5, 0xf2, 0xb3, 0xda, 0x90, 0x77, 0xbd, 0xb9, 0x86, 0x07,
	0x6a, 0x0b, 0x0f, 0xd5, 0x9e, 0xce, 0xe7, 0xa5, 0x88, 0x79, 0x79, 0xb5, 0xc4, 0xdb, 0x1a, 0x9e,
	0x16, 0xc6, 0x65, 0x17, 0x40, 0xea, 0xc2, 0xbd, 0x57, 0xe5, 0xde, 0x88, 0x88, 0xbd, 0xc9, 0x0e,
	0x68, 0x03, 0x37, 0x4a, 0x1e, 0x71, 0x6d, 0x4f, 0xd9, 0x2f, 0xd1, 0xd2, 0xc0, 0x8d, 0xe4, 0x23,
	0x3d, 0x83, 0x92, 0x1f, 0x39, 0x2e, 0xe7, 0xee, 0x9d, 0xb9, 0x8e, 0x77, 0xeb, 0x7e, 0xd4, 0x10,
	0x47, 0xeb, 0x18, 0xaa, 0xf9, 0x99, 0xa4, 0x02, 0x5a, 0xaf, 0xd1, 0xbe, 0xb2, 0x9d, 0x8e, 0xdd,
	0x35, 0x56, 0xc8, 0x13, 0xd0, 0xe5, 0xd1, 0xa6, 0xf4, 0x82, 0x1a, 0x0a, 0x31, 0xa0, 0x2c, 0x81,
	0x24, 0x59, 0xea, 0xf5, 0x1a, 0xfe, 0x0b, 0x1c, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x53,
	0x83, 0x3a, 0x1b, 0x06, 0x00, 0x00,
}
